package com.example.frontend.presentation.navigation

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val OTP_SENDED = "otp_sended_screen"
    const val FORGOT_PASSWORD_EMAIL = "forgot_password_email"
    const val FORGOT_PASSWORD_OTP_BASE = "forgot_password_otp"
    const val FORGOT_PASSWORD_OTP = "$FORGOT_PASSWORD_OTP_BASE?email={email}"
    const val FORGOT_PASSWORD_RESET_BASE = "forgot_password_reset"
    const val FORGOT_PASSWORD_RESET = "$FORGOT_PASSWORD_RESET_BASE?email={email}&otp={otp}"
    const val HOME = "home"
    const val PROFILE = "profile"
    const val OTHER_PROFILE_BASE = "other_profile"
    const val OTHER_PROFILE = "$OTHER_PROFILE_BASE/{userId}"
    const val VIDEO_BASE = "video"
    const val VIDEO = "$VIDEO_BASE?postId={postId}&videoUrl={videoUrl}"
    const val OTHER_FRIENDS_BASE = "other_friends"
    const val OTHER_FRIENDS = "$OTHER_FRIENDS_BASE/{userId}"
    const val VIDEO = "video"
    const val SEARCH = "search"
    const val NOTIFICATION = "notification"
    const val CONVERSATION_LIST = "conversation_list"
    const val CHAT_BASE = "chat"
    const val CHAT = "chat/{conversationId}?partnerId={partnerId}&name={name}&avatar={avatar}"
    const val CHAT_PROFILE_BASE = "chat_profile"
    const val CHAT_PROFILE = "$CHAT_PROFILE_BASE/{partnerId}?name={name}&avatar={avatar}&conversationId={conversationId}"
    const val SETTING ="setting"
    const val EDIT_PROFILE = "edit_profile"
    const val CHANGE_PASSWORD = "change_password"
    const val ADMIN = "admin_dashboard"
    const val ADMIN_USER_PROFILE_BASE = "admin_user_profile"
    const val ADMIN_USER_PROFILE = "$ADMIN_USER_PROFILE_BASE/{userId}?locked={locked}"
    const val CREATE_POST = "create_post"
    const val EDIT_POST_BASE = "edit_post"
    const val EDIT_POST = "$EDIT_POST_BASE/{postId}"
    const val POST_DETAIL_BASE = "post_detail"
    const val POST_DETAIL = "$POST_DETAIL_BASE/{postId}"
    const val FRIEND_REQUESTS = "friend_requests"
    const val CALL_BASE = "call"
    const val CALL = "$CALL_BASE/{targetUserId}?isVideoCall={isVideoCall}&isIncoming={isIncoming}&fullname={fullname}&avatarUrl={avatarUrl}"
    const val MY_FRIENDS = "my_friends"
    
}
